ID_SPLIT_SYMBOL = "\u2534"
NAME_BORDER_SYMBOL = "\u2506"
MATCHING_INDEXES_SPLITTER_SYMBOL = "\u256f"
UTILITY_COL_SYMBOL = "\u23e3"
UTILITY_INDEX_COL_NAME = "\u23e3index"

UTILITY_INDEX_COL_NAME = "\u23e3index"
UTILITY_PHYSICAL_INDEX_COL_NAME = "\u23e3_physical_index"

NUMBER_TYPES_LIST = [int, float]
